/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-06-11 07:49:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.pages.pos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class commonquery_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/taglib/fmt.tld", Long.valueOf(1298367396000L));
    _jspx_dependants.put("/WEB-INF/taglib/fn.tld", Long.valueOf(1298367396000L));
    _jspx_dependants.put("/WEB-INF/taglib/c.tld", Long.valueOf(1298367396000L));
    _jspx_dependants.put("/jsp/common/taglibs.jsp", Long.valueOf(1384842742068L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_fmt_005fsetBundle_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_fmt_005fsetBundle_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_fmt_005fsetBundle_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tpostracking.form.init({\r\n");
      out.write("\t\t\tisAjax:false,\r\n");
      out.write("\t\t\tajaxOptions:{\r\n");
      out.write("\t\t           dataType:'',\r\n");
      out.write("\t\t           success:function(){\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\thideLoading();\t\t\t\t\t\t\r\n");
      out.write("\t\t           }\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    fn:function(){\r\n");
      out.write("\r\n");
      out.write("\t\t    \tvar isBranch = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.isBranch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\r\n");
      out.write("\t\t    \t$(\"#deleteBtn\").click(function(){\t  \t  \t    \t\r\n");
      out.write("\t\t    \t\tpostracking.Msg.confirm(\"Confirmation\",\"Are you sure want to delete the selected item(s) ?\",{\r\n");
      out.write("\t   \t\t              \"No\":function(){\r\n");
      out.write("\t   \t\t            \t\tpostracking.Msg.closeDlg($(this));\r\n");
      out.write("\t   \t\t              },\r\n");
      out.write("\t   \t\t              \"Yes\":function(){         \r\n");
      out.write("\t\t   \t\t            \tvar selectedRows = $('#grid').getGridParam(\"selarrrow\");\r\n");
      out.write("\t\t    \t\t\t\t\t//var params = $(\"form\", \"#dialogMessage\").serialize();\r\n");
      out.write("\t\t    \t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t    \t\t\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t    \t\t\t\t\t\turl:postrackingcontextpath + '/query/delete?id=' + selectedRows,\r\n");
      out.write("\t\t    \t\t\t\t\t\t//data:params,\r\n");
      out.write("\t\t    \t\t\t\t\t\tsuccess:function(data){\t\t\t    \t\t\t\t\t\t\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tif(data.result == 'success'){\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t$(\"#grid\").trigger('reloadGrid');\t\t\t\t   \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$('#deleteBtn').attr('disabled','disabled');\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\talert(\"Error, Failed to delete record\");\r\n");
      out.write("\t\t\t\t\t    \t\t\t\t}\r\n");
      out.write("\t\t\t\t   \t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\tfailure:function(){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\talert(\"Error, Failed to delete record\");\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\tdataType:'json'\r\n");
      out.write("\t\t    \t\t\t\t\t});\t   \t   \t\t\t\t\t\r\n");
      out.write("\t\t    \t\t\t\t\tpostracking.Msg.closeDlg($(this));\r\n");
      out.write("\t\t   \t\t\t\t\t\treturn true;\r\n");
      out.write("\t   \t\t              }\r\n");
      out.write("\t   \t            });\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t  \t    \t});\r\n");
      out.write("\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t$(\"#cancelBtn\").click(function(){\t  \t  \t    \t\r\n");
      out.write("\t\t    \t\tpostracking.Msg.confirm(\"Confirmation\",\"Are you sure want to cancel the selected item(s) ?\",{\r\n");
      out.write("\t   \t\t              \"No\":function(){\r\n");
      out.write("\t   \t\t            \t\tpostracking.Msg.closeDlg($(this));\r\n");
      out.write("\t   \t\t              },\r\n");
      out.write("\t   \t\t              \"Yes\":function(){         \r\n");
      out.write("\t\t   \t\t            \tvar selectedRows = $('#grid').getGridParam(\"selarrrow\");\r\n");
      out.write("\t\t    \t\t\t\t\t//var params = $(\"form\", \"#dialogMessage\").serialize();\r\n");
      out.write("\t\t    \t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t    \t\t\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t    \t\t\t\t\t\turl:postrackingcontextpath + '/query/cancel?id=' + selectedRows,\r\n");
      out.write("\t\t    \t\t\t\t\t\t//data:params,\r\n");
      out.write("\t\t    \t\t\t\t\t\tsuccess:function(data){\t\t\t    \t\t\t\t\t\t\r\n");
      out.write("\t\t\t    \t\t\t\t\t\tif(data.result == 'success'){\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t$(\"#grid\").trigger('reloadGrid');\t\t\t\t   \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$('#cancelBtn').attr('disabled','disabled');\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\talert(\"Error, Failed to cancel record\");\r\n");
      out.write("\t\t\t\t\t    \t\t\t\t}\r\n");
      out.write("\t\t\t\t   \t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\tfailure:function(){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\talert(\"Error, Failed to cancel record\");\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\tdataType:'json'\r\n");
      out.write("\t\t    \t\t\t\t\t});\t   \t   \t\t\t\t\t\r\n");
      out.write("\t\t    \t\t\t\t\tpostracking.Msg.closeDlg($(this));\r\n");
      out.write("\t\t   \t\t\t\t\t\treturn true;\r\n");
      out.write("\t   \t\t              }\r\n");
      out.write("\t   \t            });\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t  \t    \t});\r\n");
      out.write("\t  \t    \t\r\n");
      out.write("\r\n");
      out.write("\t  \t    \t$('#btnSearchQuery').click(function(){\r\n");
      out.write("\t\t    \t\t$(\"#grid\").setGridParam({\r\n");
      out.write("\t\t\t    \t\turl \t\t\t: postrackingcontextpath+\"/query/getPosTransaction?policyNumber=\" + $('#policyNumber').val() +\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t\"&subDate=\" + $('#subDate').val() +\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t\"&posNumber=\" + $('#posNumber').val() +\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t\"&policyHolder=\" + $('#policyHolder').val() +\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t\"&branch=\" + $('#branchCombo').val() +\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t\t\"&status=\" + $('#statusQueryCombo').val(),\r\n");
      out.write("\t\t\t    \t\tloadComplete\t:function(){\r\n");
      out.write("\t\t\t    \t\t\tvar ids = jQuery(\"#grid\").jqGrid('getDataIDs');\r\n");
      out.write("\t\t\t\t\t\t\tif(ids.length == ''){\r\n");
      out.write("\t\t\t\t\t\t\t\t// do nothing\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t    \t\t}\r\n");
      out.write("\t\t    \t\t});\r\n");
      out.write("\t\t    \t\t$(\"#grid\").trigger(\"reloadGrid\");\r\n");
      out.write("\t\t  \t    });\r\n");
      out.write("\t\t  \t    \r\n");
      out.write("\r\n");
      out.write("\t\t  \t    $('#btnCancelQuery').click(function(){\r\n");
      out.write("\t\t  \t    \t$('#policyNumber').val(\"\");\r\n");
      out.write("\t\t  \t    \t$('#subDate').val(\"\");\r\n");
      out.write("\t\t  \t    \t$('#posNumber').val(\"\");\r\n");
      out.write("\t\t  \t    \t$('#policyHolder').val(\"\");\r\n");
      out.write("\t\t\t  \t});\r\n");
      out.write("\t\t  \t    \r\n");
      out.write("\r\n");
      out.write("\t\t    \tvar idsOfSelectedRows = [];\r\n");
      out.write("\t\t    \tvar updateIdsOfSelectedRows = function (id, isSelected) {\r\n");
      out.write("\t\t    \t\tvar index = $.inArray(id, idsOfSelectedRows);\t\t    \t\t\r\n");
      out.write("\t\t            if (!isSelected && index >= 0) {\r\n");
      out.write("\t\t                idsOfSelectedRows.splice(index, 1); // remove id from the list\r\n");
      out.write("\t\t            } else if (index < 0) {\t\t\t            \r\n");
      out.write("\t\t                idsOfSelectedRows.push(id);\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t    \t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t    \t$(\"#grid\").jqGrid({\r\n");
      out.write("\t\t\t\t\tdatatype: \"json\",\r\n");
      out.write("\t\t\t\t\turl: postrackingcontextpath+\"/query/getPosTransaction\",\r\n");
      out.write("\t\t\t\t\tcolNames:['&nbsb;','Pos No','Transaction No','Policy No','Transaction Type','Branch','Receive Date','Submision Date','Policy Holder','Doc Complete','Status',''],\r\n");
      out.write("\t\t\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'posTranTypePosNumberId',index:'posTranTypePosNumberId', hidden: true, width:'100px'},\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'posTranTypePosNumber',index:'posTranTypePosNumber', align:\"center\",sortable: true}, \r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'posTranTypeTransactionNumber',index:'posTranTypeTransactionNumber', align:\"center\",sortable: true},\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'policyCode',index:'policyCode',align:\"center\", sortable: true, width:'120px'},\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'posTranTypeDesc',index:'posTranTypeDesc',align:\"center\", sortable: true},\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'branch',index:'branch',align:\"center\",sortable: false, width:'90px'},\t\r\n");
      out.write("\t\t\t\t\t\t\t\t/*\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'submissionDate',index:'submissionDate', sorttype: 'date', align:'center', formatter: 'date',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tformatter: function (cellval, opts) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(cellval) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar date = new Date(cellval);\r\n");
      out.write("\t\t\t\t                            opts = $.extend({}, $.jgrid.formatter.date, opts);\r\n");
      out.write("\t\t\t\t                            return $.fmatter.util.DateFormat(\"\", date, 'd-M-Y', opts);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\t\t\t                            \r\n");
      out.write("\t\t\t                    },\t\t\t\r\n");
      out.write("\t\t\t                    */\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'receivedDate',index:'receivedDate', sorttype: 'date', align:'center', formatter: 'date', width:'120px', \r\n");
      out.write("\t\t\t                    \tformatter: function (cellval, opts) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(cellval) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar date = new Date(cellval);\r\n");
      out.write("\t\t\t\t                            opts = $.extend({}, $.jgrid.formatter.date, opts);\r\n");
      out.write("\t\t\t\t                            return $.fmatter.util.DateFormat(\"\", date, 'd-M-Y', opts);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\t\t\t                            \r\n");
      out.write("\t\t\t                    },\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'submissionDate',index:'submissionDate', sorttype: 'date', align:'center', formatter: 'date',\r\n");
      out.write("\t\t\t                    \tformatter: function (cellval, opts) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(cellval) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar date = new Date(cellval);\r\n");
      out.write("\t\t\t\t                            opts = $.extend({}, $.jgrid.formatter.date, opts);\r\n");
      out.write("\t\t\t\t                            return $.fmatter.util.DateFormat(\"\", date, 'd-M-Y', opts);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\t\t\t                            \r\n");
      out.write("\t\t\t                    },\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'policyHolder',index:'policyHolder',align:\"center\",sortable: false},\t\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'documentComplete',index:'documentComplete',align:\"center\",sortable: false, width:'130px'},\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'status',index:'status',align:\"center\",sortable: false, width:'110px'},\r\n");
      out.write("\t\t\t\t\t\t\t\t{name:'edit',index:'edit',sortable: false, align:\"center\", width:'120px'}\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t],\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tgridComplete : function(){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar ids = jQuery(\"#grid\").jqGrid('getDataIDs');\t\t\t\t\t\t\t \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar url;\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar img;\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfor ( var i = 0; i < ids.length; i++) {\t\t\t  \t\t\t\t\t\t\t  \t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar id = ids[i];\r\n");
      out.write("\t\t\t\t\t\t\tvar rowData = $('#grid').jqGrid('getRowData',ids[i]);\r\n");
      out.write("\t\t\t\t\t\t\tvar posNumber = rowData['posTranTypePosNumber'];\r\n");
      out.write("\t\t\t\t\t\t\tvar docComplete = rowData['documentComplete'];\r\n");
      out.write("\t\t\t\t\t\t\tvar status = rowData['status'];\r\n");
      out.write("\t\t\t\t\t\t\tvar commonquery = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(isBranch == 'true'){\r\n");
      out.write("\t\t\t\t\t\t\t\turl = '<a href=\"register?postrantypeid='+id+'&posnumber='+posNumber+'&commonquery='+commonquery+'\\\" id=\\\"'+id+'\\\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/eye-icon.png\" /></a>';\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\turl = '<a href=\"registerho?postrantypeid='+id+'&posnumber='+posNumber+'&commonquery='+commonquery+'\\\" id=\\\"'+id+'\\\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/eye-icon.png\" /></a>';\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif(docComplete == '200'){\r\n");
      out.write("\t\t\t\t\t\t\t\timg = \"<img src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/checked.gif' />\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(docComplete == '400'){\r\n");
      out.write("\t\t\t\t\t\t\t\timg = \"<img src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/unchecked.gif' />\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar be1 = url;\r\n");
      out.write("\t\t\t\t\t\t\tvar be2 = img;\t\t\t  \t\t\t\t\t\t\t  \t\t\t\t\t\t\t  \t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t  \t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#grid\").jqGrid('setRowData', ids[i], {\r\n");
      out.write("\t\t\t\t\t\t\t\tedit : be1,\r\n");
      out.write("\t\t\t\t\t\t\t\tdocumentComplete : be2\r\n");
      out.write("\t\t  \t\t\t\t\t});\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t  \t\t},\r\n");
      out.write("\t\t\t        onSelectAll: function (aRowids, status) {\t\t\t\t        \r\n");
      out.write("\t\t\t            var i, count, id;\r\n");
      out.write("\t\t\t            for (i = 0, count = aRowids.length; i < count; i++) {\r\n");
      out.write("\t\t\t                id = aRowids[i];\r\n");
      out.write("\t\t\t                updateIdsOfSelectedRows(id, status);\r\n");
      out.write("\t\t\t            }\t\t\t            \r\n");
      out.write("\t\t\t            if(status == true){\r\n");
      out.write("\t\t\t            \t$('#deleteBtn').removeAttr('disabled');\t\r\n");
      out.write("\t\t\t\t\t\t\t$('#cancelBtn').removeAttr('disabled');\r\n");
      out.write("\t\t\t\t        }else{\r\n");
      out.write("\t\t\t\t\t\t\t$('#deleteBtn').attr('disabled','disabled');\r\n");
      out.write("\t\t\t\t\t\t\t$('#cancelBtn').attr('disabled','disabled');\r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t  \t\tmultiselect: true,\r\n");
      out.write("\t\t\t  \t\trowNum : 10,\r\n");
      out.write("\t\t\t  \t\trowList : [ 10, 20, 30, 40, 50 ],\r\n");
      out.write("\t\t\t  \t\tpager : \"#pGrid\",\r\n");
      out.write("\t\t\t  \t\tpgbuttons: true,\r\n");
      out.write("\t\t\t  \t\tsortname : 'posNumberId',\r\n");
      out.write("\t\t\t  \t\tviewrecords : false,\r\n");
      out.write("\t\t\t  \t\tcaption: \"Result\",\r\n");
      out.write("\t\t\t  \t\tsortorder : \"desc\",\r\n");
      out.write("\t\t\t  \t\tjsonReader : {\r\n");
      out.write("\t\t\t\t\t\trepeatitems : false,\r\n");
      out.write("\t\t\t\t\t\tid: 0\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\theight : '100%',\r\n");
      out.write("\t\t\t\t\twidht : '100%',\r\n");
      out.write("\t\t\t\t\tmtype : 'GET',\t\t\r\n");
      out.write("\t\t\t\t\taltRows: true,\r\n");
      out.write("\t\t\t\t\tmultiboxonly: true,\r\n");
      out.write("\t\t\t\t\tautowidth: true,\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tonSelectRow : function(rowId, status) {\r\n");
      out.write("\t\t\t\t\t\tvar selectedRows = $('#grid').getGridParam(\"selarrrow\");\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(selectedRows.length>0) {\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$('#deleteBtn').removeAttr('disabled');\t\r\n");
      out.write("\t\t\t\t\t\t\t$('#cancelBtn').removeAttr('disabled');\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif($('.cbox:unchecked','#grid').length == 0){\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#cb_grid').attr('checked',true);\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#cb_grid').attr('checked',false);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$('#deleteBtn').attr('disabled','disabled');\r\n");
      out.write("\t\t\t\t\t\t\t$('#cancelBtn').attr('disabled','disabled');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tupdateIdsOfSelectedRows(rowId, status);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tloadComplete : function(){\r\n");
      out.write("\t\t\t\t\t\tvar $this = $(this), i, count;\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t        for (i = 0, count = idsOfSelectedRows.length; i < count; i++) {\r\n");
      out.write("\t\t\t\t            $this.jqGrid('setSelection', idsOfSelectedRows[i], false);\r\n");
      out.write("\t\t\t\t        }\r\n");
      out.write("\t\t\t\t        $(this).find(\">tbody>tr.jqgrow:odd\").addClass(\"myAltRowClassEven\");\r\n");
      out.write("\t\t\t\t        $(this).find(\">tbody>tr.jqgrow:even\").addClass(\"myAltRowClassOdd\");\r\n");
      out.write("\t\t\t\t\t}\t  \t\t\t  \t\t\t\t\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\r\n");
      out.write("\t\t    \t$(\"#statusQueryCombo\").loadOptions(postrackingcontextpath+\"/query/getStatus\",{\r\n");
      out.write("\t\t\t\t\tafterLoaded:function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#statusQueryCombo\").children(\"option[selected=selected]\").attr(\"selected\",\"\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#statusQueryCombo\").children(\"option[value=\"+$('#statusQueryFor').val()+\"]\").attr(\"selected\",\"selected\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t    \t$(\"#branchCombo\").loadOptions(postrackingcontextpath+\"/query/getBranch\",{\r\n");
      out.write("\t\t\t\t\tafterLoaded:function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#branchCombo\").children(\"option[selected=selected]\").attr(\"selected\",\"\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#branchCombo\").children(\"option[value=\"+$('#branchFor').val()+\"]\").attr(\"selected\",\"selected\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t$(\"#newBtn\").click(function(){\t\t\t    \t\t\r\n");
      out.write("\t\t\t\t\tif(isBranch == 'true') window.location.href = 'register';\r\n");
      out.write("\t\t\t\t\telse window.location.href = 'registerho';\t\t\t\t\t\r\n");
      out.write("\t\t    \t});\t\t  \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"input\").keyup(function(e) {\r\n");
      out.write("\t\t\t\t\tif (e.which == 13) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#btnSearchQuery\").click();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userRole}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' == '2' || '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userRole}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' == '1'){\r\n");
      out.write("\t\t\t\t\t$(\"#cancelBtn\").show();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#cancelBtn\").hide();\r\n");
      out.write("\t\t\t\t} \t\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetBundle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setBundle
    org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag _jspx_th_fmt_005fsetBundle_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag) _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag.class);
    _jspx_th_fmt_005fsetBundle_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetBundle_005f0.setParent(null);
    // /jsp/common/taglibs.jsp(6,0) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f0.setBasename("msg.glb");
    // /jsp/common/taglibs.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f0.setVar("glb");
    // /jsp/common/taglibs.jsp(6,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f0.setScope("application");
    int _jspx_eval_fmt_005fsetBundle_005f0 = _jspx_th_fmt_005fsetBundle_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetBundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fsetBundle_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setBundle
    org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag _jspx_th_fmt_005fsetBundle_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag) _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag.class);
    _jspx_th_fmt_005fsetBundle_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetBundle_005f1.setParent(null);
    // /jsp/common/taglibs.jsp(7,0) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f1.setBasename("msg.common");
    // /jsp/common/taglibs.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f1.setVar("com");
    // /jsp/common/taglibs.jsp(7,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f1.setScope("application");
    int _jspx_eval_fmt_005fsetBundle_005f1 = _jspx_th_fmt_005fsetBundle_005f1.doStartTag();
    if (_jspx_th_fmt_005fsetBundle_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fsetBundle_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setBundle
    org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag _jspx_th_fmt_005fsetBundle_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag) _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag.class);
    _jspx_th_fmt_005fsetBundle_005f2.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetBundle_005f2.setParent(null);
    // /jsp/common/taglibs.jsp(8,0) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f2.setBasename("msg.user");
    // /jsp/common/taglibs.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f2.setVar("usr");
    // /jsp/common/taglibs.jsp(8,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f2.setScope("application");
    int _jspx_eval_fmt_005fsetBundle_005f2 = _jspx_th_fmt_005fsetBundle_005f2.doStartTag();
    if (_jspx_th_fmt_005fsetBundle_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fscope_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /jsp/pages/pos/commonquery.jsp(6,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\t\r\n");
        out.write("\t\t<div class=\"alignclear ui-widget\">\r\n");
        out.write("\t\t\t<div class=\"alignclear ui-state-message\">\r\n");
        out.write("\t\t\t\t<ul>\r\n");
        out.write("\t\t\t\t\t<span  style=\"float: left; margin-right: 0.3em;\" class=\"ui-icon ui-icon-info\"></span><strong>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</strong>\r\n");
        out.write("\t\t\t\t</ul>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /jsp/pages/pos/commonquery.jsp(16,1) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/query");
    // /jsp/pages/pos/commonquery.jsp(16,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setVar("query");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /jsp/pages/pos/commonquery.jsp(17,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("post");
    // /jsp/pages/pos/commonquery.jsp(17,1) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setModelAttribute("user");
    // /jsp/pages/pos/commonquery.jsp(17,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${query}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\r\n");
          out.write("\t\t<div id=\"content\" class=\"widget stacked\">\r\n");
          out.write("\t\r\n");
          out.write("\t\t\t<div class=\"widget-header\">\r\n");
          out.write("\t      \t\t<i class=\"icon-book\"></i>\r\n");
          out.write("\t      \t\t<h3>POS / Common Query</h3>\r\n");
          out.write("\t  \t\t</div> <!-- /widget-header -->\r\n");
          out.write("\t  \t\t\r\n");
          out.write("\t  \t\t<div class=\"widget-content\">\r\n");
          out.write("\t  \t\t\r\n");
          out.write("\t  \t\t\t<div class=\"row-fluid\">\r\n");
          out.write("\t  \t\t\t\r\n");
          out.write("\t  \t\t\t\t<div class=\"span6\">\r\n");
          out.write("\t  \t\t\r\n");
          out.write("\t\t\t  \t\t\t<div class=\"control-group\">\r\n");
          out.write("\t\t\t  \t\t\t\t<label class=\"control-label\" for=\"name\">\r\n");
          out.write("\t\t\t  \t\t\t\t\t");
          if (_jspx_meth_fmt_005fmessage_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t  \t\t\t\t</label>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
          out.write("\t\t\t\t\t        \t<input type=\"text\" class=\"input-large\" name=\"policyNumber\" id=\"policyNumber\" />\r\n");
          out.write("\t\t\t\t\t      \t</div>\r\n");
          out.write("\t\t\t  \t\t\t</div>  \r\n");
          out.write("\t\t\t  \t\t\t\r\n");
          out.write("\t\t\t  \t\t\t<div class=\"control-group\">\r\n");
          out.write("\t\t\t  \t\t\t\t<label class=\"control-label\" for=\"name\">\t\t\t  \t\t\t\t\r\n");
          out.write("\t\t\t  \t\t\t\t\t");
          if (_jspx_meth_fmt_005fmessage_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t  \t\t\t\t</label>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
          out.write("\t\t\t\t\t        \t<input type=\"text\" class=\"input-large\" name=\"policyHolder\" id=\"policyHolder\" />\r\n");
          out.write("\t\t\t\t\t      \t</div>\r\n");
          out.write("\t\t\t  \t\t\t</div>\r\n");
          out.write("\t\t\t  \t\t\t\t\t\r\n");
          out.write("\t\t\t  \t\t\t<!--  \r\n");
          out.write("\t\t\t  \t\t\t<div class=\"control-group\">\r\n");
          out.write("\t\t\t  \t\t\t\t<label class=\"control-label\" for=\"validateSelect\">\r\n");
          out.write("\t\t\t  \t\t\t\t\t");
          if (_jspx_meth_fmt_005fmessage_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t  \t\t\t\t</label>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
          out.write("\t\t\t        \t\t\t<select id=\"validateSelect\" name=\"validateSelect\">\r\n");
          out.write("\t\t\t\t\t                <option value=\"\" />Select One\r\n");
          out.write("\t\t\t\t\t                <option value=\"1\" />1\r\n");
          out.write("\t\t\t\t\t                <option value=\"2\" />2\r\n");
          out.write("\t\t\t\t\t                <option value=\"3\" />3\r\n");
          out.write("\t\t\t\t\t                <option value=\"4\" />4\r\n");
          out.write("\t\t\t\t\t                <option value=\"5\" />5\r\n");
          out.write("\t\t\t\t\t             </select>\r\n");
          out.write("\t\t\t\t\t      \t</div>\r\n");
          out.write("\t\t\t  \t\t\t</div>\t\r\n");
          out.write("\t\t\t  \t\t\t-->\r\n");
          out.write("\t\t\t  \t\t\t<div class=\"control-group\">\r\n");
          out.write("\t\t\t  \t\t\t\t<label class=\"control-label\" for=\"validateSelect\">\r\n");
          out.write("\t\t\t  \t\t\t\t\t");
          if (_jspx_meth_fmt_005fmessage_005f3(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t  \t\t\t\t</label>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
          out.write("\t\t\t        \t\t\t<select id=\"statusQueryCombo\" name=\"validateSelect\"></select>\r\n");
          out.write("\t\t\t        \t\t\t<input type=\"hidden\" id=\"statusQueryFor\">\r\n");
          out.write("\t\t\t\t\t      \t</div>\r\n");
          out.write("\t\t\t  \t\t\t</div>  \t\r\n");
          out.write("\t\t  \t\t\t\r\n");
          out.write("\t\t  \t\t\t</div><!-- span6 -->\r\n");
          out.write("\t\t  \t\t\t\r\n");
          out.write("\t\t  \t\t\t<div class=\"span6\">\r\n");
          out.write("\t\t  \t\t\t\r\n");
          out.write("\t\t\t  \t\t\t<div class=\"control-group\">\r\n");
          out.write("\t\t\t  \t\t\t\t<label class=\"control-label\" for=\"name\">\t\t\t  \t\t\t\t\r\n");
          out.write("\t\t\t  \t\t\t\t\t");
          if (_jspx_meth_fmt_005fmessage_005f4(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t  \t\t\t\t</label>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
          out.write("\t\t\t\t\t        \t<input type=\"text\" class=\"input-large\" name=\"posNumber\" id=\"posNumber\" />\r\n");
          out.write("\t\t\t\t\t      \t</div>\r\n");
          out.write("\t\t\t  \t\t\t</div>  \t\r\n");
          out.write("\t\t\t  \t\t\t\r\n");
          out.write("\t\t\t  \t\t\t<div class=\"control-group\">\r\n");
          out.write("\t\t\t  \t\t\t\t<label class=\"control-label\" for=\"name\">\r\n");
          out.write("\t\t\t  \t\t\t\t\t");
          if (_jspx_meth_fmt_005fmessage_005f5(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t  \t\t\t\t</label>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
          out.write("\t\t\t\t\t        \t<input type=\"text\" class=\"datefield\" name=\"subDate\" id=\"subDate\" />\r\n");
          out.write("\t\t\t\t\t      \t</div>\r\n");
          out.write("\t\t\t  \t\t\t</div>\t  \t\r\n");
          out.write("\t\t\t  \t\t\t\r\n");
          out.write("\t\t\t  \t\t\t<div class=\"control-group\">\r\n");
          out.write("\t\t\t  \t\t\t\t<label class=\"control-label\" for=\"validateSelect\">\t\t\t  \t\t\t\t\r\n");
          out.write("\t\t\t  \t\t\t\t\t");
          if (_jspx_meth_fmt_005fmessage_005f6(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t  \t\t\t\t</label>\r\n");
          out.write("\t\t\t  \t\t\t\t<div class=\"controls\">\r\n");
          out.write("\t\t\t        \t\t\t<select id=\"branchCombo\" name=\"validateSelect\"></select>\r\n");
          out.write("\t\t\t        \t\t\t<input type=\"hidden\" id=\"branchFor\">\r\n");
          out.write("\t\t\t\t\t      \t</div>\r\n");
          out.write("\t\t\t  \t\t\t</div>\t\t  \t\t\t\t\t  \t\t\t\t\t\r\n");
          out.write("\t\t\t  \t\t\t  \t\t\t\t\r\n");
          out.write("\t\t  \t\t\t\r\n");
          out.write("\t\t  \t\t\t</div>\r\n");
          out.write("\t  \t\t\t\r\n");
          out.write("\t  \t\t\t</div><!-- row-fluid -->\r\n");
          out.write("\t  \t\t\t\r\n");
          out.write("\t  \t\t\t<div class=\"form-actions\">\r\n");
          out.write("\t\t\t    \t<button type=\"button\" id=\"btnSearchQuery\" name=\"btnSearchQuery\" class=\"btn btn-warning\">");
          if (_jspx_meth_fmt_005fmessage_005f7(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</button>\r\n");
          out.write("\t\t\t      \t<button type=\"reset\" id=\"btnCancelQuery\" name=\"btnCancelQuery\" class=\"btn\">");
          if (_jspx_meth_fmt_005fmessage_005f8(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</button>\r\n");
          out.write("\t\t\t\t</div>\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<!---   Begin JQgrid Table & Paging --->\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<table id=\"grid\" width=\"100%\" align=\"center\"></table>\r\n");
          out.write("\t\t\t\t<div id=\"pGrid\"></div>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<!---   End JQgrid Table & Paging  --->\t\t\t\t\t\t \r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t</div><!-- widget-content -->\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/pages/pos/commonquery.jsp(34,10) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setKey("lbl.Query.form.PolicyNumber");
    // /jsp/pages/pos/commonquery.jsp(34,10) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${com}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/pages/pos/commonquery.jsp(43,10) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f1.setKey("lbl.Query.form.PolicyHolder");
    // /jsp/pages/pos/commonquery.jsp(43,10) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f1.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${com}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/pages/pos/commonquery.jsp(53,10) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f2.setKey("lbl.Query.form.TransactionType");
    // /jsp/pages/pos/commonquery.jsp(53,10) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f2.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${com}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/pages/pos/commonquery.jsp(69,10) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f3.setKey("lbl.Query.form.Status");
    // /jsp/pages/pos/commonquery.jsp(69,10) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f3.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${com}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/pages/pos/commonquery.jsp(83,10) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f4.setKey("lbl.Query.form.PosNumber");
    // /jsp/pages/pos/commonquery.jsp(83,10) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f4.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${com}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fmessage_005f4 = _jspx_th_fmt_005fmessage_005f4.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f5 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/pages/pos/commonquery.jsp(92,10) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f5.setKey("lbl.Query.form.SubmissionDate");
    // /jsp/pages/pos/commonquery.jsp(92,10) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f5.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${com}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fmessage_005f5 = _jspx_th_fmt_005fmessage_005f5.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f6 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/pages/pos/commonquery.jsp(101,10) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f6.setKey("lbl.Query.form.Branch");
    // /jsp/pages/pos/commonquery.jsp(101,10) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f6.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${com}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fmessage_005f6 = _jspx_th_fmt_005fmessage_005f6.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f7 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/pages/pos/commonquery.jsp(115,96) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f7.setKey("btn.search");
    // /jsp/pages/pos/commonquery.jsp(115,96) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f7.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${com}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fmessage_005f7 = _jspx_th_fmt_005fmessage_005f7.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f8 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f8.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/pages/pos/commonquery.jsp(116,85) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f8.setKey("btn.cancel");
    // /jsp/pages/pos/commonquery.jsp(116,85) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f8.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${com}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fmessage_005f8 = _jspx_th_fmt_005fmessage_005f8.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f8);
    return false;
  }
}
